import { useEffect, useRef } from 'react'

interface AdsterraNativeProps {
  /** `invoke.js` URL, verbatim from the unit's snippet. */
  src: string
  /** Container id, verbatim. Adsterra's loader looks up this EXACT element. */
  container: string
}

/**
 * One Adsterra **Native Banner** unit.
 *
 * Unlike the plain banner, this format's `invoke.js` is async and fills a container `<div>` by id
 * rather than calling `document.write`, so it can be injected straight into the page and inherits
 * the page width like the in-feed AdSense unit it replaces.
 *
 * Config arrives as props rather than being read from module constants, because it now comes from
 * runtime `app-config.json` — that is what lets one build serve many cafés.
 *
 * ### Only one per page, and why no id suffix
 *
 * The container id is generated by Adsterra and their loader looks up that exact element, so an
 * obvious-looking trick — suffixing `-0`, `-1` per slot to keep ids unique — makes the script
 * match nothing and every slot stays empty. The real constraint is that a page can carry exactly
 * one native unit. The first instance to mount claims it; later ones render nothing, which is what
 * stops `MenuView` (a slot every few items) emitting several divs sharing one id.
 */
let containerClaimed = false

export default function AdsterraNative({ src, container }: AdsterraNativeProps) {
  const hostRef = useRef<HTMLDivElement | null>(null)
  const injected = useRef(false)
  // Decided once at first render so the claim cannot flip mid-life and unmount a live ad.
  const isOwner = useRef<boolean | null>(null)
  if (isOwner.current === null) {
    isOwner.current = !containerClaimed
    if (isOwner.current) containerClaimed = true
  }

  useEffect(() => {
    if (!isOwner.current) return
    return () => {
      // Release on unmount so a later mount can claim it again.
      containerClaimed = false
    }
  }, [])

  useEffect(() => {
    if (!isOwner.current || injected.current || !src || !container) return
    const host = hostRef.current
    if (!host) return
    injected.current = true

    const script = document.createElement('script')
    script.async = true
    script.setAttribute('data-cfasync', 'false')
    script.src = src
    script.onerror = () => {
      // Non-fatal: an ad blocker or dead zone just means no ad this session.
    }
    host.appendChild(script)

    return () => {
      script.remove()
      injected.current = false
    }
  }, [src, container])

  if (!src || !container || !isOwner.current) return null

  return (
    // Width-capped and centred rather than full-bleed. A Native Banner lays its items out in a
    // responsive grid, so an unconstrained container on a wide screen renders more columns and a
    // taller block. Capping the width keeps the footprint predictable without clipping the unit —
    // `overflow:hidden` on an ad is the wrong tool: it hides paid impressions and reads as
    // cloaking to the network.
    //
    // The real height control is the ROW/COLUMN setting on the unit itself in the Adsterra
    // dashboard; nothing in this file can shrink a unit configured to render many rows.
    <div ref={hostRef} className="mx-auto w-full max-w-sm py-2" aria-hidden="true">
      <div id={container} />
    </div>
  )
}
