package com.razstudio.pos.data

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * A staff device registered successfully and then failed forever on the very next call.
 *
 * There are two device ids, and the backend uses each in different places:
 *
 *  - `devices.device_identifier` — the client-generated UUID the app sends. `admin-handshake` and
 *    `admin-recovery` look up by this.
 *  - `devices.id` — the row's primary key, generated by Postgres on insert. `devices-status`,
 *    `devices` and `attendance` look up by *this*.
 *
 * `register/index.ts` inserts `device_identifier: deviceId` and then returns `{ deviceId: device.id }`
 * — the *server* key, under a name identical to the one the caller just sent. Every caller therefore
 * kept using its own UUID, and `devices-status?deviceId=<client uuid>` resolved
 * `.eq("id", <client uuid>)` against a primary key that could never match: a permanent
 * `404 NOT_FOUND`, immediately after a successful registration.
 *
 * That is the reported symptom exactly — "404 directly after the QR is scanned, never waits for the
 * admin handshake". The device was not failing to register; it was failing to find itself.
 *
 * Cloud Mode only. `LocalBackend.register` returns the client id as `deviceId`, because on a LAN
 * server the two genuinely are the same value — which is why the fallback below must be preserved.
 */
@RunWith(RobolectricTestRunner::class)
class ServerDeviceIdTest {

    private lateinit var storage: SecureStorage

    /** What Postgres generates — deliberately unlike the client UUID the app would send. */
    private val serverRowId = "7f3a9c21-0b44-4e58-9d10-2a6b5c8e1f00"

    private lateinit var prefs: android.content.SharedPreferences

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        // Plain prefs, injected through the test seam: EncryptedSharedPreferences needs a real
        // Keystore, which Robolectric has none of, so the real backing store silently returns null
        // for every read and getDeviceId() would mint a new UUID per call.
        prefs = context.getSharedPreferences("server_device_id_test", Context.MODE_PRIVATE)
        prefs.edit().clear().commit()
        storage = SecureStorage(context, prefs)
    }

    @Test
    fun beforeRegistrationTheServerIdFallsBackToTheLocalOne() {
        // LAN Mode depends on this: LocalBackend hands back the client id, so the two are one value
        // and nothing in that topology needs to change.
        assertEquals(storage.getDeviceId(), storage.getServerDeviceId())
    }

    @Test
    fun afterRegistrationPollingUsesTheServerRowKey() {
        val localId = storage.getDeviceId()
        storage.setServerDeviceId(serverRowId)

        assertEquals("polls must carry the server's row key", serverRowId, storage.getServerDeviceId())
        assertNotEquals(
            "the two ids are different values — conflating them is the whole bug",
            localId, storage.getServerDeviceId(),
        )
    }

    @Test
    fun theLocalIdSurvivesUnchanged() {
        // `admin-handshake` and `admin-recovery` still look up by device_identifier, so the local id
        // must not be overwritten by the server's.
        val localId = storage.getDeviceId()
        storage.setServerDeviceId(serverRowId)

        assertEquals(localId, storage.getDeviceId())
    }

    @Test
    fun aBlankOrNullLiteralIsNeverStored() {
        // A mis-parsed response must not replace a working id with garbage that would 404 forever.
        storage.setServerDeviceId(serverRowId)
        storage.setServerDeviceId("")
        storage.setServerDeviceId("null")

        assertEquals(serverRowId, storage.getServerDeviceId())
    }

    @Test
    fun itPersistsAcrossProcessDeath() {
        // PendingApprovalScreen polls after the app may have been killed and reopened; an in-memory
        // id would send the device back to a 404 loop with no way out but re-registering.
        storage.setServerDeviceId(serverRowId)

        val reopened = SecureStorage(ApplicationProvider.getApplicationContext(), prefs)
        assertEquals(serverRowId, reopened.getServerDeviceId())
    }

    @Test
    fun theRegisterResponseFieldIsTheServerKeyNotTheClientOne() {
        // Documents the contract that caused this, so a future reader does not "simplify" the caller
        // back to its own UUID: register's response field is named `deviceId` but holds `devices.id`.
        val parsed = RegisterResponse(deviceId = serverRowId, status = "PENDING")

        assertEquals(serverRowId, parsed.deviceId)
        assertTrue("registration always lands PENDING, awaiting admin approval", parsed.status == "PENDING")
    }
}
